[package]
name = "flipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.13"
futures = "0.3"
macroquad = { version = "0.4.5", features = ["audio"] }

[dev-dependencies]
float-cmp = "0.9.0"
