name: DevSkim
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '15 19 * * 5'
permissions:
  contents: read
jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@0aa4037a25755a8a5bd422d7a5b0b8ba7971863b # v1.0.13
      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@3ab4101902695724f9365a384f86c1074d94e18c # v3.24.7
        with:
          sarif_file: devskim-results.sarif
